---
name: readme

"on":
  push:
    branches:
      - master
    paths:
      - README.md
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Push readme
        uses: actionhippie/pushrm@3be2dcf048c674aef56b79f086e40198c0b4ba3b # v1
        if: github.event_name != 'pull_request'
        with:
          provider: dockerhub
          target: webhippie/gitea
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          description: Docker image for gitea
          readme: README.md

      - name: Push readme
        uses: actionhippie/pushrm@3be2dcf048c674aef56b79f086e40198c0b4ba3b # v1
        with:
          provider: quay
          target: quay.io/webhippie/gitea
          apikey: ${{ secrets.QUAY_APIKEY }}
          readme: README.md

...
