---
name: readme

"on":
  push:
    branches:
      - master
    paths:
      - README.md
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Push readme
        uses: actionhippie/pushrm@2f7e4beeb0c27f1c319e85ef5bb7cf3a420e9d96 # v1
        if: github.event_name != 'pull_request'
        with:
          provider: dockerhub
          target: webhippie/gitea
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          description: Docker image for gitea
          readme: README.md

      - name: Push readme
        uses: actionhippie/pushrm@2f7e4beeb0c27f1c319e85ef5bb7cf3a420e9d96 # v1
        with:
          provider: quay
          target: quay.io/webhippie/gitea
          apikey: ${{ secrets.QUAY_APIKEY }}
          readme: README.md

...
